---
- hosts: all

  vars:
    user: vagrant
    group: vagrant
    java_packages:
      - oracle-java7-installer
    spark_version: 1.4.1-bin-hadoop2.6
    scala_versions: ["2.11.7"]
    scala_default_version: "2.11.7"
    scala_sbt_version: "0.13.9"

  roles:
#    - { role: desktop, sudo: true }
    - { role: jyunderwood.java8, sudo: true }
    - { role: ANXS.scala, sudo: true }
    - { role: jgoodall.maven3, maven_version: 3.3.3, sudo: true }
    - { role: alban.andrieu.eclipse, sudo: true }
#    - { role: idea }
#    - { role: code-retreat }

  tasks:
    - name: Setup the JAVA_HOME
      lineinfile:
        dest=/home/{{user}}/.bashrc
        line="export JAVA_HOME=/usr/lib/jvm/java-8-oracle/"
